# Generated by Django 5.1.2 on 2024-10-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link_type',
            field=models.CharField(default='website', max_length=50),
        ),
    ]
